title = "イロイロラボ！"
theme = "mainroad"
baseurl = "https://iroirolab.com/"
#baseurl = "https://nyagbon.github.io/iroiro"
paginate = "10" # Number of posts per page
DefaultContentLanguage = "ja"
languageCode = "ja-jp"
disqusShortname = "iroirolab" # Enable Disqus comments by entering your Disqus shortname
googleAnalytics = "G-FWNCXL1TP8" # Enable Google Analytics by entering your tracking id
googleAdsense = "ca-pub-5611995804803519"
hasCJKLanguage = true
enableEmoji = true
pygmentsUseClasses= true  # syntax highlight with chromastyles
pygmentsCodefences = true # enable chromastyles also in three backticks
enableRobotsTXT = true

[Author] # Used in authorbox
  name = "にゃご"
  bio = "テレワーク太り。Python 好き。Emacs 使い。デジタルガジェット好き。大阪生まれ東京育ち。会社員。PC-6001 が原体験。$\\rm{\\TeX}$ 世代。"
  avatar = "img/mymii.png"

[Permalinks]
  post = "/:sections/:year/:month/:slug/"

[Params]
  description = "Nyago's personal blog about everything, mainly about software engineering and digital stuff" # Site description. Used in meta description
  copyright = "iroirolab.com" # Footer copyright holder, otherwise will use site title
  images = [ "img/nyago-big.png" ]
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = false # Enable Twitter Cards if true
  my_twitter_cards = true # Enable My Own Twitter Cards if true
  my_twitter_card_type = "summary" # card type, one of summary, summary_large_image, app, or player
  readmore = true # Show "Read more" button in list if true
  authorbox = true # Show authorbox at bottom of pages if true
  toc = false # Enable Table of Contents
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  # post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
  post_meta = ["date", "categories"] # Order of post meta information
  mainSections = ["post", "news"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "2006-01-02" # Change the format of dates
  mathjax = true # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Load Google Fonts
  customCSS = ["css/custom.css", "css/code-title.css", "css/syntax.css"] # Include custom CSS files
  customJS = ["js/custom.js", "js/code-title.js"] # Include custom JS files
  share = true

[Params.style.vars]
  highlightColor = "#c20000" # Override highlight color

  # Override font-family sets. Secondary font-family set responsible for pre, code, kbd, and samp tags font
  # Take care of different quotes OR escaping symbols in these params if necessary
  fontFamilyPrimary = "'Open Sans', Helvetica, Arial, 'Hiragino Kaku GOthic ProN', 'Meiryo', sans-serif"
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[Params.logo]
  # image = "img/placeholder.png" # Logo image. Path relative to "static"
  image = "img/nyago-big.png" # Logo image. Path relative to "static"
  title = "イロイロラボ！ iroirolab.com" # Logo title, otherwise will use site title
  subtitle = "にゃごのデジタル実験室(とか戯言とか)" # Logo subtitle

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = true # Configure layout for single pages
  # Enable widgets in given order
  # widgets = ["search", "recent", "categories", "taglist", "social"]
  widgets = ["recent", "categories", "taglist", "archives", "social"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[Params.widgets]
  recent_num = 10 # Set the number of articles in the "Recent articles" widget
  categories_counter = true # Enable counter for each category in "Categories" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  # Enable parts of social widget
  # facebook = "username"
  twitter = "nyagbon"
  # instagram = "username"
  # linkedin = "username"
  # telegram = "username"
  github = "nyagbon"
  # gitlab = "username"
  # bitbucket = "username"
  # email = "example@example.com"

# Custom social links
[[Params.widgets.social.custom]]
    title = "Reddit"
    url = "https://reddit.com/user/nyagbon"
    # icon = "svg/iconmonstr-reddit-4.svg"
    # icon = "svg/reddit-logo-2436.svg"
    icon = "fab fa-reddit-alien"

[[Params.widgets.social.custom]]
    title = "RSS"
    url = "/index.xml"
    # icon = "svg/iconmonstr-reddit-4.svg"
    icon = "fas fa-rss"
    # icon = "svg/reddit-logo-2436.svg"

#   title = "Youtube"
#   url = "https://youtube.com/user/username"
#   icon = "youtube.svg" # Optional. Path relative to "layouts/partials"

# [[Params.widgets.social.custom]]
#   title = "My Home Page"
#   url = "http://example.com"

