name: github pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false    # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify

      - name: Pre-Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
       
      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: ./public/*
          remote: ~/public
          host: ${{ secrets.IROIRO_HOST }}
          port: ${{ secrets.IROIRO_PORT }}
          user: ${{ secrets.IROIRO_USER }}
          key: ${{ secrets.IROIRO_KEY }}

// Parameters with prefix 'proxy' are optional.

      - name: SCP Upload
        uses: betanzos/scp-upload@v1
        with:
          source: ./public
          port: ${{ secrets.IROIRO_PORT }}
          host: ${{ secrets.IROIRO_HOST }}
          username: ${{ secrets.IROIRO_USER }}
          key: ${{ secrets.IROIRO_KEY }}
          remote_dir: '~'
